# Generated by Django 5.1.3 on 2024-11-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SleepSchedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepschedule',
            name='sleep_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sleepschedule',
            name='wake_time',
            field=models.CharField(max_length=10),
        ),
    ]
