# Generated by Django 5.1.1 on 2024-10-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressTracking',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('goal', models.CharField(max_length=50)),
                ('progress_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SleepTrack',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('sleep_duration', models.TimeField()),
                ('sleep_quality', models.CharField(max_length=15)),
                ('sleep_stages', models.CharField(max_length=15)),
                ('schedule_id', models.IntegerField()),
            ],
        ),
    ]
