# Generated by Django 5.1.1 on 2024-11-07 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelaxationRoutine',
            fields=[
                ('routineID', models.AutoField(primary_key=True, serialize=False)),
                ('routineType', models.CharField(max_length=100)),
                ('routineStartTime', models.TimeField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.user')),
            ],
        ),
    ]
