# Generated by Django 5.1.3 on 2024-12-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_user_first_name_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wake_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
