# Generated by Django 5.1.1 on 2024-12-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_user_wake_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sleepTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
