# Generated by Django 5.1.1 on 2024-12-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_add_user_id_to_sleeptrack'),
        ('tracker', '0007_user_sleeptime'),
    ]

    operations = [
    ]
